# Generated by Django 4.1.13 on 2025-11-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_orderitems_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.order'),
            preserve_default=False,
        ),
    ]
