# Generated by Django 4.1.13 on 2025-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
